runtime: custom
env: flex

# Lock instances to 1
manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 1000
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5